//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4335.Windows.Klopov4335
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsrpoEntities : DbContext
    {
        public IsrpoEntities()
            : base("name=IsrpoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        private static IsrpoEntities _context = new IsrpoEntities();

        public static IsrpoEntities GetContext()
        {
            if (_context == null)
                _context = new IsrpoEntities();
            return _context;
        }

        public virtual DbSet<sotrydniki> sotrydniki { get; set; }
    }
}
