//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4335.Windows.Klopov4335
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class sotrydniki
    {
        [JsonPropertyName("Position")]
        public string role_e { get; set; }

        [JsonPropertyName("FullName")]
        public string fio_e { get; set; }

        [JsonPropertyName("Log")]
        public string login_e { get; set; }

        [JsonPropertyName("Password")]
        public string pass_e { get; set; }
    }
}
